name: "Angular update"

on:
  push
  schedule:
    - cron:  '0 2 * * *'

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Updating ng dependencies
        uses: tinesoft/ngx-uptodate@v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
