name: "Angular update"

on:
  schedule:
    - cron:  '15 14 * * *'

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    needs: [ci/circleci: build]
    steps:
      - name: Updating ng dependencies
        uses: tinesoft/ngx-uptodate@v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-labels: ng-update, automated pr, automerge
